// <auto-generated />
using ImportadorCadastroEan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace ImportadorCadastroEan.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImportadorCadastroEan.Modelos.Produto", b =>
                {
                    b.Property<Guid>("GuidProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Cest")
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DescricaoAcento")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DescricaoNormalizada")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DescricaoUpper")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Embalagem")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FotoGif")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FotoPng")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FotoTabloideGif")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FotoTabloidePng")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gtin")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImgGtin")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ncm")
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Peso")
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("GuidProduto");

                    b.ToTable("BaseProdutosEan");
                });
#pragma warning restore 612, 618
        }
    }
}
